### ISSUE TITLE
Mu.Server.wrapServer seems to segfault

### ISSUE THREAD

**Issue by bens** [higherkindness/mu-haskell#289]
I tried using the `wrapServer` function but can only get segfaults. I've reduced my code down to a very minimal example so hopefully that's helpful.

`schema.graphql`:
```graphql
type Query { hello: String! }
```

`Main.hs`:
```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PartialTypeSignatures #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeFamilies #-}
{-# OPTIONS_GHC -fno-warn-partial-type-signatures #-}

module Main where

import Data.Proxy (Proxy (Proxy))
import Mu.GraphQL.Quasi (graphql)
import Mu.GraphQL.Server (runGraphQLAppQuery)
import Mu.Server (MonadServer, ServerT, method, object, resolver, wrapServer)

graphql "ServiceDefinition" "schema.graphql"

segv :: Bool
segv = False

main :: IO ()
main = do
  putStrLn "starting GraphQL server on port 8000"
  let wrapper = if segv then wrapServer (const id) else id
  runGraphQLAppQuery 8000 (wrapper server) (Proxy @"Query")

server :: MonadServer m => ServerT '[] i ServiceDefinition m _
server = resolver (object @"Query" (method @"hello" $ pure "hello"))
```
`wrapserver-segv.cabal`:
```
cabal-version: >=2.0
name: wrapserver-segv
version: 0.1.0.0
build-type: Simple

executable wrapserver-segv
  main-is: Main.hs
  build-depends:
    base >=4.13 && <4.14,
    mu-graphql ^>=0.5.0, mu-rpc ^>=0.5.0, mu-schema ^>=0.3.1
  ghc-options: -Wall
  default-language: Haskell2010
```

Querying the server works fine with `segv = False`, but the server segfaults when querying it with `segv = True`.

```shell
$ curl -sS http://localhost:8000 -H 'Content-Type: application/json' -d '{"query": "{ hello }"}'
curl: (52) Empty reply from server
```

`const id` is the most minimal wrapper I could think of, just passing back the given `m a` value and ignoring the `RpcInfo`.
