### ISSUE TITLE
mu-grahpql and mu-grpc-client version problem

### ISSUE THREAD

**Issue by todd-kim** [higherkindness/mu-haskell#320]
Hi!
I'm working api gateway server with mu-graphql.
It's work very well so far. But I'm going to use a grpc client in mu-graphql project.
I think, there is a version conflict between mu-graphql and mu-grpc-client.
```
mu-grpc-client-0.4.0.1 -> http2-client-grpc (==0.8.*) ->  http2 (>=1.6 && <2.1)
mu-graphql-0.5.0.2-> warp (>=3.3 && <4)
```
`mu-grpc-client-0.4.0.1` needs to `http2 (>=1.6 && <2.1)` but `warp 3.3` needs to `http2 (==2.0.*)`.
How can I solve this problem?
`* The arrow means depends on.`

**Comment by todd-kim** [comment]
I've solved by myself. 
There is `http2-client-grpc` version using `http2-client-0.10.0.0` on [there repository](https://github.com/haskell-grpc-native/http2-grpc-haskell.git). 
So I added extra-deps as git repo instead of hackage as following:
```
- git: https://github.com/haskell-grpc-native/http2-grpc-haskell.git
  commit: d7da6d63a16a1e9d16f20f5c50a29a1c42c3d354
  subdirs:
    - http2-client-grpc
```
